# Generated by Django 3.2 on 2026-01-09 11:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ('cms', '0022_auto_20180620_1551'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryPlugin',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='content_plugins_galleryplugin', serialize=False, to='cms.cmsplugin')),
                ('title', models.CharField(max_length=200, verbose_name='Gallery Title')),
                ('description', models.TextField(blank=True, help_text='Optional description text', verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Gallery',
                'verbose_name_plural': 'Galleries',
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='PeopleGridPlugin',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='content_plugins_peoplegridplugin', serialize=False, to='cms.cmsplugin')),
                ('title', models.CharField(default='Our Team', max_length=200, verbose_name='Section Title')),
            ],
            options={
                'verbose_name': 'People Grid',
                'verbose_name_plural': 'People Grids',
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='YouTubeEmbedPlugin',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='content_plugins_youtubeembedplugin', serialize=False, to='cms.cmsplugin')),
                ('video_title', models.CharField(max_length=200, verbose_name='Video Title')),
                ('youtube_id', models.CharField(help_text="Enter the YouTube video ID (e.g., 'dQw4w9WgXcQ' from youtube.com/watch?v=dQw4w9WgXcQ)", max_length=50, verbose_name='YouTube Video ID')),
            ],
            options={
                'verbose_name': 'YouTube Embed',
                'verbose_name_plural': 'YouTube Embeds',
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('job_title', models.CharField(max_length=200, verbose_name='Job Title/Description')),
                ('profile_link', models.URLField(blank=True, help_text='Link to full profile page', verbose_name='Profile Link')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Order')),
                ('people_grid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='people', to='content_plugins.peoplegridplugin')),
                ('photo', filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='person_photos', to=settings.FILER_IMAGE_MODEL, verbose_name='Photo')),
            ],
            options={
                'verbose_name': 'Person',
                'verbose_name_plural': 'People',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='IntroSlidePlugin',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='content_plugins_introslideplugin', serialize=False, to='cms.cmsplugin')),
                ('headline', models.CharField(help_text='Main headline text', max_length=200, verbose_name='Headline')),
                ('sub_headline', models.TextField(help_text='Supporting text below the headline', verbose_name='Sub-headline')),
                ('background_image', filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='intro_slide_backgrounds', to=settings.FILER_IMAGE_MODEL, verbose_name='Background Image')),
            ],
            options={
                'verbose_name': 'Intro Slide',
                'verbose_name_plural': 'Intro Slides',
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='HistoryBlockPlugin',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='content_plugins_historyblockplugin', serialize=False, to='cms.cmsplugin')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('body_text', models.TextField(help_text='Main content text', verbose_name='Body Text')),
                ('image', filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history_block_images', to=settings.FILER_IMAGE_MODEL, verbose_name='Image')),
            ],
            options={
                'verbose_name': 'History Block',
                'verbose_name_plural': 'History Blocks',
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='Caption')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Order')),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='content_plugins.galleryplugin')),
                ('image', filer.fields.image.FilerImageField(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to=settings.FILER_IMAGE_MODEL, verbose_name='Image')),
            ],
            options={
                'verbose_name': 'Gallery Image',
                'verbose_name_plural': 'Gallery Images',
                'ordering': ['order'],
            },
        ),
    ]
