# Generated by Django 4.2.27 on 2026-01-13 02:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ('content_plugins', '0002_alter_galleryplugin_cmsplugin_ptr_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeopleGridImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(blank=True, help_text='Optional caption for the lightbox', max_length=200, verbose_name='Caption')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Order')),
                ('image', filer.fields.image.FilerImageField(on_delete=django.db.models.deletion.CASCADE, related_name='people_grid_extra_images', to=settings.FILER_IMAGE_MODEL, verbose_name='Image')),
                ('people_grid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_images', to='content_plugins.peoplegridplugin')),
            ],
            options={
                'verbose_name': 'Grid Image',
                'verbose_name_plural': 'Grid Images',
                'ordering': ['order'],
            },
        ),
    ]
