# Generated by Django 4.2.27 on 2026-01-13 03:02

from django.db import migrations
import django.db.models.deletion
import filer.fields.folder


class Migration(migrations.Migration):

    dependencies = [
        ('filer', '0017_image__transparent'),
        ('content_plugins', '0003_peoplegridimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryplugin',
            name='folder',
            field=filer.fields.folder.FilerFolderField(blank=True, help_text='Select a folder to auto-populate the gallery. Images will be used from here.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='filer.folder', verbose_name='Source Folder'),
        ),
    ]
