# Generated by Django 4.2.27 on 2026-01-14 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_plugins', '0004_galleryplugin_folder'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryplugin',
            name='department_title',
            field=models.CharField(default='Department of Physical and Macromolecular Chemistry', help_text='Identity text displayed at the top of the slide', max_length=200, verbose_name='Department Title'),
        ),
        migrations.AddField(
            model_name='historyblockplugin',
            name='department_title',
            field=models.CharField(default='Department of Physical and Macromolecular Chemistry', help_text='Identity text displayed at the top of the slide', max_length=200, verbose_name='Department Title'),
        ),
        migrations.AddField(
            model_name='introslideplugin',
            name='department_title',
            field=models.CharField(default='Department of Physical and Macromolecular Chemistry', help_text='Identity text displayed at the top of the slide', max_length=200, verbose_name='Department Title'),
        ),
        migrations.AddField(
            model_name='peoplegridplugin',
            name='department_title',
            field=models.CharField(default='Department of Physical and Macromolecular Chemistry', help_text='Identity text displayed at the top of the slide', max_length=200, verbose_name='Department Title'),
        ),
        migrations.AddField(
            model_name='youtubeembedplugin',
            name='department_title',
            field=models.CharField(default='Department of Physical and Macromolecular Chemistry', help_text='Identity text displayed at the top of the slide', max_length=200, verbose_name='Department Title'),
        ),
    ]
