# Generated by Django 4.2.27 on 2026-01-14 13:30

from django.conf import settings
from django.db import migrations
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ('content_plugins', '0005_galleryplugin_department_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryplugin',
            name='department_logo',
            field=filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_logos', to=settings.FILER_IMAGE_MODEL, verbose_name='Department Logo'),
        ),
        migrations.AddField(
            model_name='historyblockplugin',
            name='department_logo',
            field=filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_logos', to=settings.FILER_IMAGE_MODEL, verbose_name='Department Logo'),
        ),
        migrations.AddField(
            model_name='introslideplugin',
            name='department_logo',
            field=filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_logos', to=settings.FILER_IMAGE_MODEL, verbose_name='Department Logo'),
        ),
        migrations.AddField(
            model_name='peoplegridplugin',
            name='department_logo',
            field=filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_logos', to=settings.FILER_IMAGE_MODEL, verbose_name='Department Logo'),
        ),
        migrations.AddField(
            model_name='youtubeembedplugin',
            name='department_logo',
            field=filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_logos', to=settings.FILER_IMAGE_MODEL, verbose_name='Department Logo'),
        ),
    ]
