# Generated by Django 4.2.27 on 2026-01-14 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_plugins', '0006_galleryplugin_department_logo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryplugin',
            name='department_website',
            field=models.URLField(default='https://www.natur.cuni.cz/chemistry/fyzchem', help_text='URL for the QR code', max_length=500, verbose_name='Department Website'),
        ),
        migrations.AddField(
            model_name='historyblockplugin',
            name='department_website',
            field=models.URLField(default='https://www.natur.cuni.cz/chemistry/fyzchem', help_text='URL for the QR code', max_length=500, verbose_name='Department Website'),
        ),
        migrations.AddField(
            model_name='introslideplugin',
            name='department_website',
            field=models.URLField(default='https://www.natur.cuni.cz/chemistry/fyzchem', help_text='URL for the QR code', max_length=500, verbose_name='Department Website'),
        ),
        migrations.AddField(
            model_name='peoplegridplugin',
            name='department_website',
            field=models.URLField(default='https://www.natur.cuni.cz/chemistry/fyzchem', help_text='URL for the QR code', max_length=500, verbose_name='Department Website'),
        ),
        migrations.AddField(
            model_name='youtubeembedplugin',
            name='department_website',
            field=models.URLField(default='https://www.natur.cuni.cz/chemistry/fyzchem', help_text='URL for the QR code', max_length=500, verbose_name='Department Website'),
        ),
    ]
