# Generated by Django 4.2.27 on 2026-01-14 14:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ('cms', '0035_auto_20230822_2208_squashed_0036_auto_20240311_1028'),
        ('content_plugins', '0007_galleryplugin_department_website_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModernSlidePlugin',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('department_title', models.CharField(default='Department of Physical and Macromolecular Chemistry', help_text='Identity text displayed at the top of the slide', max_length=200, verbose_name='Department Title')),
                ('department_website', models.URLField(default='https://www.natur.cuni.cz/chemistry/fyzchem', help_text='URL for the QR code', max_length=500, verbose_name='Department Website')),
                ('title', models.CharField(default='Modern Highlights', max_length=200, verbose_name='Slide Title')),
                ('department_logo', filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_logos', to=settings.FILER_IMAGE_MODEL, verbose_name='Department Logo')),
            ],
            options={
                'verbose_name': 'Modern Grid Slide',
                'verbose_name_plural': 'Modern Grid Slides',
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='ModernSlideItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtitle', models.CharField(blank=True, max_length=200, verbose_name='Subtitle/Label')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Order')),
                ('image', filer.fields.image.FilerImageField(on_delete=django.db.models.deletion.CASCADE, related_name='modern_slide_images', to=settings.FILER_IMAGE_MODEL, verbose_name='Image')),
                ('plugin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='content_plugins.modernslideplugin')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
