# Generated by Django 4.2.27 on 2026-01-16 01:37

from django.conf import settings
from django.db import migrations
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ('content_plugins', '0009_scientificgroupplugin_researchitem_groupmember'),
    ]

    operations = [
        migrations.AddField(
            model_name='scientificgroupplugin',
            name='background_image',
            field=filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scientific_group_backgrounds', to=settings.FILER_IMAGE_MODEL, verbose_name='Background Image'),
        ),
    ]
