# Generated by Django 4.2.27 on 2026-01-16 02:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0035_auto_20230822_2208_squashed_0036_auto_20240311_1028'),
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ('content_plugins', '0010_scientificgroupplugin_background_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='AwardsPlugin',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('department_title', models.CharField(default='Department of Physical and Macromolecular Chemistry', help_text='Identity text displayed at the top of the slide', max_length=200, verbose_name='Department Title')),
                ('department_website', models.URLField(default='https://www.natur.cuni.cz/chemistry/fyzchem', help_text='URL for the QR code', max_length=500, verbose_name='Department Website')),
                ('title', models.CharField(default='Our Awards', max_length=200, verbose_name='Slide Title')),
                ('background_image', filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='awards_slide_backgrounds', to=settings.FILER_IMAGE_MODEL, verbose_name='Background Image')),
                ('department_logo', filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_logos', to=settings.FILER_IMAGE_MODEL, verbose_name='Department Logo')),
            ],
            options={
                'verbose_name': 'Awards Slide',
                'verbose_name_plural': 'Awards Slides',
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='AwardItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Award Title')),
                ('recipient', models.CharField(max_length=200, verbose_name='Recipient')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Order')),
                ('image', filer.fields.image.FilerImageField(on_delete=django.db.models.deletion.CASCADE, related_name='award_images', to=settings.FILER_IMAGE_MODEL, verbose_name='Award Image')),
                ('plugin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awards', to='content_plugins.awardsplugin')),
            ],
            options={
                'verbose_name': 'Award',
                'verbose_name_plural': 'Awards',
                'ordering': ['order'],
            },
        ),
    ]
