# Generated by Django 4.2.27 on 2026-01-16 03:04

from django.db import migrations
import djangocms_text_ckeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('content_plugins', '0011_awardsplugin_awarditem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='awardsplugin',
            name='title',
        ),
        migrations.AddField(
            model_name='awardsplugin',
            name='content',
            field=djangocms_text_ckeditor.fields.HTMLField(default="<h1 class='title-large'>OUR AWARDS</h1>", help_text='Edit title and subtitles here', verbose_name='Content'),
        ),
    ]
