# Generated by Django 4.2.27 on 2026-01-16 03:06

from django.db import migrations, models
import djangocms_text_ckeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('content_plugins', '0012_remove_awardsplugin_title_awardsplugin_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='awardsplugin',
            name='title',
            field=models.CharField(blank=True, default='Our Awards', max_length=200, verbose_name='Slide Title'),
        ),
        migrations.AlterField(
            model_name='awardsplugin',
            name='content',
            field=djangocms_text_ckeditor.fields.HTMLField(default="<h1 class='title-large'>OUR AWARDS</h1>", help_text='Edit description and subtitles here', verbose_name='Content'),
        ),
    ]
