# Generated by Django 4.2.27 on 2026-01-16 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_plugins', '0013_awardsplugin_title_alter_awardsplugin_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='awardsplugin',
            name='subtitle',
            field=models.CharField(blank=True, help_text='Supporting text below the main title', max_length=500, verbose_name='Subtitle'),
        ),
    ]
