# Generated by Django 4.2.27 on 2026-01-16 03:11

from django.db import migrations
import djangocms_text_ckeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('content_plugins', '0014_awardsplugin_subtitle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='awardsplugin',
            name='content',
            field=djangocms_text_ckeditor.fields.HTMLField(blank=True, default='', help_text='Edit description and subtitles here', verbose_name='Content'),
        ),
    ]
