# Generated by Django 4.2.27 on 2026-01-16 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_plugins', '0015_alter_awardsplugin_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='awardsplugin',
            name='department_website',
            field=models.URLField(default='https://physchem.cz', help_text='URL for the QR code', max_length=500, verbose_name='Department Website'),
        ),
        migrations.AlterField(
            model_name='galleryplugin',
            name='department_website',
            field=models.URLField(default='https://physchem.cz', help_text='URL for the QR code', max_length=500, verbose_name='Department Website'),
        ),
        migrations.AlterField(
            model_name='historyblockplugin',
            name='department_website',
            field=models.URLField(default='https://physchem.cz', help_text='URL for the QR code', max_length=500, verbose_name='Department Website'),
        ),
        migrations.AlterField(
            model_name='introslideplugin',
            name='department_website',
            field=models.URLField(default='https://physchem.cz', help_text='URL for the QR code', max_length=500, verbose_name='Department Website'),
        ),
        migrations.AlterField(
            model_name='modernslideplugin',
            name='department_website',
            field=models.URLField(default='https://physchem.cz', help_text='URL for the QR code', max_length=500, verbose_name='Department Website'),
        ),
        migrations.AlterField(
            model_name='peoplegridplugin',
            name='department_website',
            field=models.URLField(default='https://physchem.cz', help_text='URL for the QR code', max_length=500, verbose_name='Department Website'),
        ),
        migrations.AlterField(
            model_name='scientificgroupplugin',
            name='department_website',
            field=models.URLField(default='https://physchem.cz', help_text='URL for the QR code', max_length=500, verbose_name='Department Website'),
        ),
        migrations.AlterField(
            model_name='youtubeembedplugin',
            name='department_website',
            field=models.URLField(default='https://physchem.cz', help_text='URL for the QR code', max_length=500, verbose_name='Department Website'),
        ),
    ]
