# Generated by Django 4.2.27 on 2026-01-16 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_plugins', '0016_alter_awardsplugin_department_website_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='youtubeembedplugin',
            name='subtitle',
            field=models.CharField(blank=True, help_text='Text to display as an overlay during video playback (optional)', max_length=500, verbose_name='Overlay Subtitle'),
        ),
        migrations.AlterField(
            model_name='awardsplugin',
            name='department_title',
            field=models.CharField(default='Katedra fyzikální a makromolekulární chemie', help_text='Identity text displayed at the top of the slide', max_length=200, verbose_name='Department Title'),
        ),
        migrations.AlterField(
            model_name='galleryplugin',
            name='department_title',
            field=models.CharField(default='Katedra fyzikální a makromolekulární chemie', help_text='Identity text displayed at the top of the slide', max_length=200, verbose_name='Department Title'),
        ),
        migrations.AlterField(
            model_name='historyblockplugin',
            name='department_title',
            field=models.CharField(default='Katedra fyzikální a makromolekulární chemie', help_text='Identity text displayed at the top of the slide', max_length=200, verbose_name='Department Title'),
        ),
        migrations.AlterField(
            model_name='introslideplugin',
            name='department_title',
            field=models.CharField(default='Katedra fyzikální a makromolekulární chemie', help_text='Identity text displayed at the top of the slide', max_length=200, verbose_name='Department Title'),
        ),
        migrations.AlterField(
            model_name='modernslideplugin',
            name='department_title',
            field=models.CharField(default='Katedra fyzikální a makromolekulární chemie', help_text='Identity text displayed at the top of the slide', max_length=200, verbose_name='Department Title'),
        ),
        migrations.AlterField(
            model_name='peoplegridplugin',
            name='department_title',
            field=models.CharField(default='Katedra fyzikální a makromolekulární chemie', help_text='Identity text displayed at the top of the slide', max_length=200, verbose_name='Department Title'),
        ),
        migrations.AlterField(
            model_name='scientificgroupplugin',
            name='department_title',
            field=models.CharField(default='Katedra fyzikální a makromolekulární chemie', help_text='Identity text displayed at the top of the slide', max_length=200, verbose_name='Department Title'),
        ),
        migrations.AlterField(
            model_name='youtubeembedplugin',
            name='department_title',
            field=models.CharField(default='Katedra fyzikální a makromolekulární chemie', help_text='Identity text displayed at the top of the slide', max_length=200, verbose_name='Department Title'),
        ),
    ]
