# Generated by Django 4.2.27 on 2026-01-16 08:59

from django.conf import settings
from django.db import migrations
import django.db.models.deletion
import filer.fields.file
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        ('filer', '0017_image__transparent'),
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ('content_plugins', '0017_youtubeembedplugin_subtitle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchitem',
            name='video_file',
            field=filer.fields.file.FilerFileField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scientific_group_research_videos', to='filer.file', verbose_name='Short Video (optional)'),
        ),
        migrations.AlterField(
            model_name='researchitem',
            name='image',
            field=filer.fields.image.FilerImageField(on_delete=django.db.models.deletion.CASCADE, related_name='scientific_group_research_images', to=settings.FILER_IMAGE_MODEL, verbose_name='Thumbnail Image'),
        ),
    ]
