# Generated by Django 4.2.27 on 2026-01-17 10:43

from django.db import migrations, models
import django.db.models.deletion
import filer.fields.file


class Migration(migrations.Migration):

    dependencies = [
        ('filer', '0017_image__transparent'),
        ('content_plugins', '0018_researchitem_video_file_alter_researchitem_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='youtubeembedplugin',
            name='video_file',
            field=filer.fields.file.FilerFileField(blank=True, help_text='Optional: Upload an .mp4 file directly (H.264 recommended)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='video_plugin_files', to='filer.file', verbose_name='Local Video File'),
        ),
        migrations.AlterField(
            model_name='youtubeembedplugin',
            name='video_title',
            field=models.CharField(help_text='Name of this slide in the CMS', max_length=200, verbose_name='Internal Title'),
        ),
        migrations.AlterField(
            model_name='youtubeembedplugin',
            name='youtube_id',
            field=models.CharField(blank=True, help_text="Optional: Enter the YouTube video ID (e.g., 'dQw4w9WgXcQ')", max_length=50, null=True, verbose_name='YouTube Video ID'),
        ),
    ]
