# Generated by Django 4.2.27 on 2026-01-17 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content_plugins', '0019_youtubeembedplugin_video_file_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='youtubeembedplugin',
            options={'verbose_name': 'Video Slide', 'verbose_name_plural': 'Video Slides'},
        ),
    ]
