# Generated by Django 4.2.27 on 2026-01-26 19:23

from django.conf import settings
from django.db import migrations
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ('content_plugins', '0020_alter_youtubeembedplugin_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='awarditem',
            name='image',
            field=filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='award_images', to=settings.FILER_IMAGE_MODEL, verbose_name='Award Image'),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='image',
            field=filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gallery_images', to=settings.FILER_IMAGE_MODEL, verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='groupmember',
            name='photo',
            field=filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scientific_group_member_photos', to=settings.FILER_IMAGE_MODEL, verbose_name='Photo'),
        ),
        migrations.AlterField(
            model_name='modernslideitem',
            name='image',
            field=filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modern_slide_images', to=settings.FILER_IMAGE_MODEL, verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='peoplegridimage',
            name='image',
            field=filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='people_grid_extra_images', to=settings.FILER_IMAGE_MODEL, verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='researchitem',
            name='image',
            field=filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scientific_group_research_images', to=settings.FILER_IMAGE_MODEL, verbose_name='Thumbnail Image'),
        ),
    ]
